### ISSUE TITLE
Create Use Case Diagram

### ISSUE THREAD

**Issue by JakubMatuszakHTD** [IIS-ZPI/ZPI2023_IO1_5D#21]

**Comment by PiotrJurek240693** [comment]
![zpinf drawio](https://github.com/IIS-ZPI/ZPI2023_IO1_5D/assets/97394316/baf6f98b-4ec8-4402-aa77-7c923cfd15d4)

**Comment by JakubMatuszakHTD** [comment]
![UCD](https://github.com/IIS-ZPI/ZPI2023_IO1_5D/assets/139873692/7e606399-16d3-42a0-a5b0-d0e91fcde70d)
