### ISSUE TITLE
Create a document with functional and non-functional assumptions

### ISSUE THREAD

**Issue by JakubMatuszakHTD** [IIS-ZPI/ZPI2023_IO1_5D#22]

**Comment by KacperM-02** [comment]
[Functional_and_non-functional_requirements.docx](https://github.com/IIS-ZPI/ZPI2023_IO1_5D/files/14668953/Functional_and_non-functional_requirements.docx)

Added Functional and non-functional requirements

**Comment by KacperM-02** [comment]
Corrected functional and non-functional requirements.



[Functional_and_non-functional_requirements.docx](https://github.com/IIS-ZPI/ZPI2023_IO1_5D/files/15052712/Functional_and_non-functional_requirements.docx)
